# # :verbose: true
# # :concurrency: 25
# # :pidfile: tmp/pids/sidekiq.pid
# # development:
# #   :concurrency: 25
# # production:
# #   :concurrency: 25
# # :queues:
# #   - authentication
# #   - requestreceiver
# #   # - [myqueue, 2]
:verbose: true
:pidfile: tmp/pids/sidekiq.pid
:concurrency: 25
# # :timeout: 30
:queues:
  - authentication
  - requestreceiver
  - audio
  - csvfile
  - generator
# # :limits:
# #     authentication: 5
# #     requestreceiver: 10
#  